export const IS_LOADED = "IS_LOADED";
export const FETCH_COMINOVEL = "FETCH_COMINOVEL";
export const FETCH_COMINOVEL_FULLFILLED = "FETCH_COMINOVEL_FULLFILLED";
export const FETCH_SEASONS = "FETCH_SEASONS";
export const FETCH_SEASONS_FULLFILLED = "FETCH_SEASONS_FULLFILLED";
